"""Auto migration

Revision ID: 2a538c2607d9
Revises: user_profile_img
Create Date: 2026-01-31 03:54:00.897115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '2a538c2607d9'
down_revision = 'user_profile_img'
branch_labels = None
depends_on = None


def upgrade():
    # Only create if table does not exist (e.g. already created by client_ratings_001).
    conn = op.get_bind()
    inspector = inspect(conn)
    if 'client_ratings' not in inspector.get_table_names():
        op.create_table('client_ratings',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('service_request_id', sa.Text(), nullable=False),
            sa.Column('client_id', sa.UUID(), nullable=False),
            sa.Column('rater_id', sa.UUID(), nullable=False),
            sa.Column('rating', sa.Integer(), nullable=False),
            sa.Column('review_text', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
            sa.CheckConstraint('rating >= 1 AND rating <= 5', name='client_rating_check_range'),
            sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_ratings')
    # ### end Alembic commands ###
