"""Add WooCommerce product types

Revision ID: 93d36564e418
Revises: 8dbf2d4506ed
Create Date: 2026-03-03 11:14:05.327378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93d36564e418'
down_revision = '8dbf2d4506ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('variations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('grouped_products', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('external_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('button_text', sa.Text(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE shop_products SET product_type = 'simple'")

    # Alter column to be NOT NULL
    with op.batch_alter_table('shop_products', schema=None) as batch_op:
        batch_op.alter_column('product_type', existing_type=sa.Text(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_products', schema=None) as batch_op:
        batch_op.drop_column('button_text')
        batch_op.drop_column('external_url')
        batch_op.drop_column('grouped_products')
        batch_op.drop_column('variations')
        batch_op.drop_column('attributes')
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###
