"""auto

Revision ID: a18f2a7a379a
Revises: 7b62ec135ddc
Create Date: 2026-02-26 01:26:21.900230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18f2a7a379a'
down_revision = '7b62ec135ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('municipality', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ward', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('ward')
        batch_op.drop_column('municipality')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
