"""Auto migration

Revision ID: ba4d47693a29
Revises: 642f420196db
Create Date: 2026-01-18 12:47:51.551945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4d47693a29'
down_revision = '642f420196db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('product_id', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['shop_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    
    # Add status column as nullable first using raw SQL to avoid batch_alter_table issues
    op.execute("ALTER TABLE shop_products ADD COLUMN status TEXT")
    
    # Update all existing rows to have 'active' status
    op.execute("UPDATE shop_products SET status = 'active' WHERE status IS NULL")
    
    # Now make the column NOT NULL
    op.execute("ALTER TABLE shop_products ALTER COLUMN status SET NOT NULL")
    
    # Add check constraint for status values
    op.execute("ALTER TABLE shop_products ADD CONSTRAINT check_product_status CHECK (status IN ('active', 'inactive'))")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop check constraint first
    op.drop_constraint('check_product_status', 'shop_products', type_='check')
    
    with op.batch_alter_table('shop_products', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('inventory')
    # ### end Alembic commands ###
