"""Auto migration

Revision ID: e662e1550dad
Revises: pending_profile_001
Create Date: 2026-02-17 12:17:25.478002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e662e1550dad'
down_revision = 'pending_profile_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('agents_agent_id_key'), type_='unique')

    with op.batch_alter_table('pending_profile_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_profile_updates_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_profile_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_profile_updates_status'), ['status'], unique=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('agents_agent_id_key'), ['agent_id'])

    # ### end Alembic commands ###
